/**
 * @author Leszek Szczotka
 * @date 03/01/2022
 * @description Utility class with all strings and labels.
 */
public class Utils {
	public static final String PHYSICAL_OFFER = 'Physical';
    public static final String VIRTUAL_OFFER = 'Virtual';
    public static final String VEHICLE_IS_ALREADY_AVAILABLE_PHYSICALLY = Label.VEHICLE_IS_ALREADY_AVAILABLE_PHYSICALLY;
    public static final String TESTING_VEHICAL = 'testCar';
    public static final String TESTING_SALON = 'testSalon';
    public static final String VIN_NUMBER = '1234567890';
    public static final String MODEL = 'testModel';
    public static final String ACCOUNT = 'TestAccount';
    public static final String TELEMETRY_TEMPERATURE = 'temperature';
}